// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Implicit flow returns tokens directly in the URL hash on the OAuth
    // callback — the deep-link handler in src/main.tsx parses
    // `#access_token=...&refresh_token=...` and calls setSession().
    flowType: 'implicit',
    detectSessionInUrl: true,
  },
  global: {
    // Late-bind to globalThis.fetch so the supabase client always uses the
    // current global fetch — important on Capacitor where CapacitorHttp
    // patches fetch after the page loads. Without this, the supabase SDK
    // captures the original WebView fetch at module-load time and on
    // Android the first call right after the OAuth deep-link wakes the
    // WebView fails with "TypeError: Failed to fetch".
    fetch: (...args: Parameters<typeof fetch>) => globalThis.fetch(...args),
  },
});